### ISSUE TITLE
Encryption Bug

### ISSUE THREAD

**Issue by Kasper-Liu** [Kasper-Liu/Kasper-Liu.github.io#3]
The encrypting module is buggy that ABC will become BLV.
Help me to Fix it pls.

**Comment by Volunteer-H** [comment]
What do you want it to become? ABC to what?

**Comment by Volunteer-H** [comment]
The code is perfect now, in the encrypt and decrypt places. Well done.

**Comment by Kasper-Liu** [comment]
No.

**Comment by Volunteer-H** [comment]
No? What do you mean?

**Comment by Kasper-Liu** [comment]
It is still buggy

**Comment by Volunteer-H** [comment]
Really? How so?

**Comment by Kasper-Liu** [comment]
ABC->BLV

**Comment by Volunteer-H** [comment]
What do you want it to be, then? ABC to MNO?
